// pickart-nuxt/pages/places/[slug].vue
<script setup lang="ts">
import type { Place, ArtPiece } from "~/types";
import { definePageMeta, useRoute, useAsyncData } from '#imports'
import { useSupabase } from '~/composables/useSupabase'

definePageMeta({
  static: true,
  revalidate: 604800, // 1 week in seconds
});

const route = useRoute();
const { getPlace, getArtPiece } = useSupabase();

// Fetch place and associated art piece at build time
const { data: place } = await useAsyncData<Place>(`place-${route.params.slug}`, () =>
  getPlace(route.params.slug as string)
);

// Fetch art piece only if place exists and has an art piece ID
const { data: artPiece } = await useAsyncData<ArtPiece | null>(
  `art-piece-${place.value?.art_piece_id}`,
  async () => {
    if (!place.value?.art_piece_id) return null;
    return getArtPiece(place.value.art_piece_id);
  }
);
</script>

<template>
  <div v-if="place" class="container mx-auto px-4 py-8">
    <div class="grid grid-cols-1 md:grid-cols-2 gap-8">
      <div>
        <NuxtImg
          :src="place.image"
          :alt="place.name"
          class="w-full rounded-lg shadow-md"
        />
      </div>
      <div>
        <h1 class="text-4xl font-bold mb-4">{{ place.name }}</h1>
        <div class="space-y-4">
          <div>
            <h3 class="font-semibold">Type</h3>
            <p class="capitalize">{{ place.type }}</p>
          </div>
          <div>
            <h3 class="font-semibold">Location</h3>
            <p>{{ place.location }}</p>
          </div>
          <div>
            <h3 class="font-semibold">Description</h3>
            <p class="text-gray-700">{{ place.description }}</p>
          </div>
          <div v-if="artPiece">
            <h3 class="font-semibold mb-2">Featured Art</h3>
            <div class="bg-gray-50 p-4 rounded-lg">
              <h4 class="text-xl font-semibold">{{ artPiece.title }}</h4>
              <p class="text-gray-600">by {{ artPiece.artist }}</p>
              <NuxtLink
                :to="`/art/${artPiece.id}`"
                class="mt-2 inline-block text-blue-600 hover:text-blue-700"
              >
                View Art Details →
              </NuxtLink>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div v-else class="container mx-auto px-4 py-8">
    <p>Place not found</p>
  </div>
</template>

// pickart/app/place/[slug]/page.tsx
import { getPlaceBySlug } from "@/lib/places"
import { getArtPieceById } from "@/lib/art"
import { notFound, redirect } from "next/navigation"
import Image from "next/image"
import Link from "next/link"

export default async function PlacePage({ params }: { params: { slug: string } }) {
  const place = await getPlaceBySlug(params.slug)

  if (!place) {
    notFound()
  }

  // If the place has an art piece assigned, redirect to the art piece page
  if (place.artPieceId) {
    const artPiece = await getArtPieceById(place.artPieceId)

    // Only redirect if the art piece exists and is published
    if (artPiece && artPiece.published) {
      redirect(`/art/${place.artPieceId}`)
    }
  }

  // If we get here, either there's no art piece assigned or it's not published
  // So we'll show a placeholder page
  return (
    <div className="container mx-auto px-4 py-12">
      <div className="max-w-3xl mx-auto text-center">
        <div className="relative h-64 w-full mb-8 rounded-lg overflow-hidden">
          <Image src={place.image || "/placeholder.svg"} alt={place.name} fill className="object-cover" />
        </div>

        <h1 className="text-3xl font-bold mb-4">{place.name}</h1>
        <p className="text-xl text-gray-600 mb-2">
          {place.type.charAt(0).toUpperCase() + place.type.slice(1)} in {place.location}
        </p>
        <p className="text-gray-700 mb-8">{place.description}</p>

        <div className="bg-gray-50 p-8 rounded-lg">
          <h2 className="text-2xl font-semibold mb-4">No Art Piece Currently Featured</h2>
          <p className="text-gray-600 mb-6">
            This {place.type} doesn't have an art piece assigned yet or the assigned piece is not currently available.
          </p>
          <Link
            href="/art"
            className="inline-block px-6 py-3 bg-black text-white rounded-md hover:bg-gray-800 transition-colors"
          >
            Browse Available Art
          </Link>
        </div>
      </div>
    </div>
  )
}
