// pickart-next/app/art/[id]/page.tsx
export const revalidate = 3600 // Revalidate every hour (3600 seconds)

import { getArtPieceById, getPublishedArtPieceIds } from "@/lib/art"
import { notFound } from "next/navigation"
import PurchaseButton from "@/components/purchase-button"
import ArtDetails from "@/components/art-details"
import ArtGallery from "@/components/art-gallery"

// Generate static pages at build time
export async function generateStaticParams() {
  const artPieces = await getPublishedArtPieceIds()

  return artPieces.map((id) => ({
    id: id.toString(),
  }))
}

// Generate metadata for SEO
export async function generateMetadata({ params }) {
  const art = await getArtPieceById(params.id)

  if (!art) {
    return {
      title: "Art Not Found | PickArt",
    }
  }

  return {
    title: `${art.title} by ${art.artist} | PickArt`,
    description: art.description,
    openGraph: {
      images: [art.images[0]],
    },
  }
}

export default async function ArtPiecePage({ params }) {
  const art = await getArtPieceById(params.id)

  if (!art || !art.published) {
    notFound()
  }

  return (
    <div className="container mx-auto px-4 py-12">
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-12">
        <ArtGallery images={art.images} title={art.title} />

        <div>
          <h1 className="text-3xl font-bold">{art.title}</h1>
          <p className="text-xl mt-2">by {art.artist}</p>
          <p className="text-gray-600 mt-1">{art.year}</p>

          <div className="mt-6">
            <p className="text-2xl font-bold">${art.price.toLocaleString()}</p>
          </div>

          <div className="mt-6">
            <PurchaseButton artPiece={art} />
          </div>

          <div className="mt-8">
            <h2 className="text-xl font-semibold mb-2">Description</h2>
            <p className="text-gray-700">{art.description}</p>
          </div>

          <ArtDetails art={art} />
        </div>
      </div>
    </div>
  )
}

// pickart-nuxt/pages/art/[id].vue
<script setup lang="ts">
import type { ArtPiece } from "~/types";
import { definePageMeta, useRoute, useAsyncData } from '#imports'
import { useSupabase } from '~/composables/useSupabase'

definePageMeta({
  static: true,
  revalidate: 604800, // 1 week in seconds
});

const route = useRoute();
const { getArtPiece } = useSupabase();

// Fetch art piece at build time
const { data: piece } = await useAsyncData<ArtPiece>(`art-piece-${route.params.id}`, () =>
  getArtPiece(route.params.id as string)
);
</script>

<template>
  <div v-if="piece" class="container mx-auto px-4 py-8">
    <div class="grid grid-cols-1 md:grid-cols-2 gap-8">
      <div class="space-y-4">
        <NuxtImg
          v-for="(image, index) in piece.images"
          :key="index"
          :src="image"
          :alt="`${piece.title} - Image ${index + 1}`"
          class="w-full rounded-lg shadow-md"
        />
      </div>
      <div>
        <h1 class="text-4xl font-bold mb-4">{{ piece.title }}</h1>
        <p class="text-xl text-gray-600 mb-6">by {{ piece.artist }}</p>
        <p class="text-3xl font-bold mb-6">
          ${{ piece.price.toLocaleString() }}
        </p>
        <div class="space-y-4">
          <p class="text-gray-700">{{ piece.description }}</p>
          <div class="grid grid-cols-2 gap-4">
            <div>
              <h3 class="font-semibold">Dimensions</h3>
              <p>{{ piece.dimensions }}</p>
            </div>
            <div>
              <h3 class="font-semibold">Medium</h3>
              <p>{{ piece.medium }}</p>
            </div>
            <div>
              <h3 class="font-semibold">Style</h3>
              <p>{{ piece.style }}</p>
            </div>
            <div>
              <h3 class="font-semibold">Year</h3>
              <p>{{ piece.year }}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div v-else class="container mx-auto px-4 py-8">
    <p>Art piece not found</p>
  </div>
</template>
