// pickart-next/app/art/page.tsx
export const revalidate = 3600 // Revalidate every hour (3600 seconds)

import { getPublishedArtPieces } from "@/lib/art"
import Link from "next/link"
import Image from "next/image"

export const metadata = {
  title: "Browse Art | PickArt",
  description: "Discover and purchase unique art pieces from talented artists around the world.",
}

export default async function ArtPage() {
  const artPieces = await getPublishedArtPieces()

  return (
    <div className="container mx-auto px-4 py-12">
      <h1 className="text-3xl font-bold mb-8">Browse Art</h1>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
        {artPieces.map((art) => (
          <Link href={`/art/${art.id}`} key={art.id} className="group">
            <div className="border rounded-lg overflow-hidden shadow-sm hover:shadow-md transition-shadow">
              <div className="relative h-64 w-full">
                <Image
                  src={art.images[0] || "/placeholder.svg"}
                  alt={art.title}
                  fill
                  className="object-cover group-hover:scale-105 transition-transform duration-300"
                />
              </div>
              <div className="p-4">
                <h2 className="text-xl font-semibold">{art.title}</h2>
                <p className="text-gray-600">{art.artist}</p>
                <p className="mt-2 font-medium">${art.price.toLocaleString()}</p>
              </div>
            </div>
          </Link>
        ))}
      </div>
    </div>
  )
}

// pickart-nuxt/pages/art/index.vue
<script setup lang="ts">
import type { ArtPiece } from "~/types";

definePageMeta({
  static: true,
  revalidate: 604800, // 1 week in seconds
});

const { getArtPieces } = useSupabase();

// Fetch art pieces at build time
const { data: artPieces } = await useAsyncData("art-pieces", async () => {
  const pieces = await getArtPieces();
  return pieces || [];
});
</script>

<template>
  <div class="container mx-auto px-4 py-8">
    <h1 class="text-4xl font-bold mb-8">Art Collection</h1>
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
      <div
        v-for="piece in artPieces"
        :key="piece.id"
        class="bg-white rounded-lg shadow-md overflow-hidden"
      >
        <NuxtImg
          :src="piece.images?.[0] || '/images/placeholder.jpg'"
          :alt="piece.title"
          class="w-full h-64 object-cover"
        />
        <div class="p-4">
          <h2 class="text-xl font-semibold mb-2">{{ piece.title }}</h2>
          <p class="text-gray-600 mb-2">by {{ piece.artist }}</p>
          <p class="text-lg font-bold">${{ piece.price.toLocaleString() }}</p>
          <NuxtLink
            :to="`/art/${piece.id}`"
            class="mt-4 inline-block bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700"
          >
            View Details
          </NuxtLink>
        </div>
      </div>
    </div>
  </div>
</template>
